from enum import Enum


class ErrorCode(str, Enum):
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    INVALID_TOKEN = "INVALID_TOKEN"
    INVALID_SIGNATURE = "INVALID_SIGNATURE"
    DECODE_ERROR = "DECODE_ERROR"
    MISSING_TOKEN = "MISSING_TOKEN"

    USER_NOT_FOUND = "USER_NOT_FOUND"
    USER_ALREADY_EXIST = "USER_ALREADY_EXIST"

    VALIDATION_ERROR = "VALIDATION_ERROR"
    INVALID_INPUT = "INVALID_INPUT"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    INVALID_EMAIL = "INVALID_EMAIL"
    INVALID_PASSWORD = "INVALID_PASSWORD"

    PERMISSION_DENIED = "PERMISSION_DENIED"
    RESOURCE_CONFLICT = "RESOURCE_CONFLICT"

    UNKNOWN_ERROR = "UNKNOWN_ERROR"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
